[Interface]
PrivateKey = iNoiaxa+GeswgKZtCAH4B+lk3owAeqUbzLiQe2PiZnQ=
Address = 10.0.0.2/24
DNS = 8.8.8.8, 1.1.1.1

[Peer]
PublicKey = 7V7V7V7V7V7V7V7V7V7V7V7V7V7V7V7V7V7V7V7V=
Endpoint = 52.16.156.56:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25