import sys

print("=== ANÁLISIS PROFUNDO V1 VS V2 ===")
print()
print("V1 (vulnerable):")
print("  for i in range(128):")
print("    payload = read_input()")
print("    A = payload['A']")
print("    FS_state = hash(A, FS_state)")
print("    challenge = FS_state[-1] & 1  # INMEDIATO")
print("    verify(A, z, challenge)")
print()
print("V2 (fixed?):")
print("  A_vals = []")
print("  for i in range(128):")
print("    payload = read_input()")
print("    A_vals.append(payload['A'])")
print("  ")
print("  # Calcular TODOS los challenges DESPUÉS")
print("  for i in range(128):")
print("    FS_state = hash(A_vals[i], FS_state)")
print("  challenges = extract_128_bits(FS_state)")
print("  ")
print("  # Verificar")
print("  for i in range(128):")
print("    verify(A_vals[i], z_vals[i], challenges[i])")
print()
print("El problema en V2:")
print("- Necesito elegir cada A antes de conocer su challenge")
print("- La probabilidad de acertar 128 bits es 2^-128")
print()
print("¿Soluciones posibles?")
print("1. Fuerza bruta: IMPOSIBLE (tomaría más que la edad del universo)")
print("2. Encontrar colisión de hash: Muy difícil con SHA256")
print("3. Explotar debilidad en Pedersen: Requiere DLOG")
print("4. ??? ALGO QUE NO ESTOY VIENDO ???")
